# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: fabric-stack-asset-transfer-guide

on:
  push:
  pull_request:
  create:
    tags:
      - "*"      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: IBM-Blockchain/ansible-collection
          path: ansiblecollection

      - name: Build Docker image
        run: |
          docker build -t ofs-ansible ansiblecollection

      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true
          version: "v0.14.0"
      - uses: extractions/setup-just@v1
      - name: production test flow
        run: |
          just kind review-config operator console

      - uses: actions/checkout@v3
        with:
          repository: hyperledger-labs/fabric-operator
          path: fabric-operator

      - name: build up fabric network
        working-directory: fabric-operator/sample-network 
        run: ls

      - name: check k8s service
        run: kubectl get service --all-namespaces
      - name: check k8s deployment
        run: kubectl get deployment --all-namespaces
